name: Playwright Tests

on:
  schedule:
    - cron: "0 6 * * *" # 6h sáng mỗi ngày
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: "Chọn test suite cần chạy"
        type: choice
        default: all
        options:
          - all
          - regression
          - webTests
          - APITests
          - SafariNewConfig

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOME: ${{ github.workspace }}
      START_TIME: ${{ github.event.workflow_run.run_started_at || github.event.created_at || github.run_started_at }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Tests
        run: |
          rm -rf allure-results || true
          rm -rf playwright-report || true

          case "${{ github.event.inputs.TEST_SUITE || 'all' }}" in
            regression|all)
              echo "▶️ Running regression tests..."
              npm run regression
              ;;
          esac

          case "${{ github.event.inputs.TEST_SUITE || 'all' }}" in
            webTests|all)
              echo "▶️ Running web UI tests..."
              npm run webTests
              ;;
          esac

          case "${{ github.event.inputs.TEST_SUITE || 'all' }}" in
            APITests|all)
              echo "▶️ Running API tests..."
              npm run APITests
              ;;
          esac

          case "${{ github.event.inputs.TEST_SUITE || 'all' }}" in
            SafariNewConfig|all)
              echo "▶️ Running Safari tests..."
              npm run SafariNewConfig
              ;;
          esac

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 5

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Calculate duration
        id: duration
        run: |
          start_ts=$(date -d "${{ env.START_TIME }}" +%s)
          end_ts=$(date +%s)
          duration=$((end_ts - start_ts))
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          echo "DURATION=${minutes}m ${seconds}s" >> $GITHUB_ENV

      - name: Send Slack notification
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#automation-report",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ job.status == 'success' && '✅' || '❌' }} ${{ github.workflow }} #${{ github.run_number }} - ${{ job.status }}",
                  "fields": [
                    {
                      "title": "Duration",
                      "value": "${{ env.DURATION }}",
                      "short": true
                    },
                    {
                      "title": "Build URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": false
                    },
                    {
                      "title": "HTML Report",
                      "value": "Playwright HTML Report (attached as artifact)",
                      "short": false
                    },
                    {
                      "title": "Allure Report",
                      "value": "Check GitHub Pages or artifact for Allure report",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
