name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: "Select test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - regression
          - webTests
          - APITests
          - SafariNewConfig
  schedule:
    - cron: "0 23 * * *" # 6h sáng VN = 23h hôm trước UTC

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOME: ${{ github.workspace }}
      TEST_SUITE: ${{ github.event.inputs.TEST_SUITE || 'all' }}
      BUILD_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Clean old reports
        run: |
          rm -rf allure-results playwright-report combined-report || true

      - name: Run tests
        run: |
          if [ "$TEST_SUITE" == "regression" ] || [ "$TEST_SUITE" == "all" ]; then
            npm run regression
          fi
        continue-on-error: true
          if [ "$TEST_SUITE" == "webTests" ] || [ "$TEST_SUITE" == "all" ]; then
            npm run webTests
          fi
        continue-on-error: true
          if [ "$TEST_SUITE" == "APITests" ] || [ "$TEST_SUITE" == "all" ]; then
            npm run APITests
          fi
        continue-on-error: true
          if [ "$TEST_SUITE" == "SafariNewConfig" ] || [ "$TEST_SUITE" == "all" ]; then
            npm run SafariNewConfig
          fi
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Prepare combined report folder
        run: |
          mkdir -p combined-report
          cp -r allure-report combined-report/allure
          cp -r playwright-report combined-report/playwright

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Playwright HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # # 🟢 Deploy cả 2 report lên GitHub Pages
      # - name: Deploy Reports to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./combined-report
      #     publish_branch: gh-pages
      #     force_orphan: true

      # 🟢 Gửi email báo kết quả kèm link report online
      - name: Send email with report links
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[${{ job.status }}] Test Report - ${{ github.workflow }} #${{ github.run_number }}"
          to: ${{ secrets.SMTP_USERNAME }}
          from: GitHub Actions ${{ secrets.SMTP_USERNAME }}
          content_type: text/html
          body: |
            Hello Team,<br><br>
            Build `orkflow }}</b> #${{ github.run_number }} đã hoàn thành với trạng thái: <b>${{ job.status }}</b>.<br><br>
            🔗 <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure/">Xem Allure Report</a><br>
            🔗 <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/playwright/">Xem Playwright HTML Report</a><br><br>
            Trân trọng,<br>
            GitHub Actions

      # 🟢 Gửi thông báo Slack format giống Jenkins
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          custom_payload: |
            {
              "text": "🔔 *${{ github.workflow }}* #${{ github.run_number }} - *${{ job.status }}*",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#36a64f' || '#ff0000' }}",
                  "fields": [
                    {
                      "title": "Build URL",
                      "value": "${{ env.BUILD_URL }}",
                      "short": false
                    },
                    {
                      "title": "📄 HTML Report",
                      "value": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/playwright/",
                      "short": false
                    },
                    {
                      "title": "📊 Allure Report",
                      "value": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure/",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
